In [2]:
import warnings
warnings.filterwarnings('ignore')
import os

import sys
module_path = os.path.abspath(os.path.join(os.pardir, os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)

import pandas as pd
import numpy as np

In [3]:
from EnergyScience.store_data import DataStore
from EnergyScience.utilities import get_month

## Feature Analysis and Engineering

In [4]:
dataset = pd.read_csv('../data1/dataset_los_angeles.csv')

In [3]:
dataset.isna().sum()

Unnamed: 0                                         0
Cooling:Electricity [kW](Hourly)                   0
Date/Time                                          0
Electricity:Facility [kW](Hourly)                  0
Fans:Electricity [kW](Hourly)                      0
Gas:Facility [kW](Hourly)                          0
Heating:Electricity [kW](Hourly)                   0
Heating:Gas [kW](Hourly)                           0
InteriorEquipment:Electricity [kW](Hourly)         0
InteriorEquipment:Gas [kW](Hourly)                 0
InteriorLights:Electricity [kW](Hourly)            0
Water Heater:WaterSystems:Gas [kW](Hourly)         0
building_type                                      0
location                                           0
location_id                                        0
building_id                                        0
Date                                               0
Holiday                                       136296
Holiday_code                                  136296
time                                               0
sunriseTime                                        0
sunsetTime                                         0
temperatureHigh                                    0
dewPoint                                           0
humidity                                           0
windSpeed                                          0
cloudCover                                         0
Electricity:Facility [kW](Hourly)_lag              0
Electricity:Facility [kW](Hourly)_future           0
Electricity:Facility_delta_current_lag             0
dtype: int64

In [4]:
dataset_expand_holidays = pd.get_dummies(dataset['Holiday'])
dataset = pd.concat([dataset, dataset_expand_holidays], axis=1)
dataset.head(5)

,Unnamed: 0,Cooling:Electricity [kW](Hourly),Date/Time,Electricity:Facility [kW](Hourly),Fans:Electricity [kW](Hourly),Gas:Facility [kW](Hourly),Heating:Electricity [kW](Hourly),Heating:Gas [kW](Hourly),InteriorEquipment:Electricity [kW](Hourly),InteriorEquipment:Gas [kW](Hourly),...,Christmas Day,Columbus Day,Independence Day,Labor Day,Martin Luther King Day,Memorial Day,New Years Day,Presidents Day,Thanksgiving,Veterans Day
0,4248,0.0,01/01 01:00:00,92.895587,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,1,0,0,0
1,4249,0.0,01/01 02:00:00,93.813660,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,1,0,0,0
2,4250,0.0,01/01 03:00:00,94.444221,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,1,0,0,0
3,4251,0.0,01/01 04:00:00,96.481468,0.0,2.915538,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,1,0,0,0
4,4252,0.0,01/01 05:00:00,102.114437,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,1,0,0,0

In [5]:
dataset = dataset.drop(columns=['Holiday_code', 'Holiday'])
weekday_features = pd.read_csv('../data1/weekday_features.csv')
weekday_features.head(5)

    Date       Day  is_weekend  is_holiday   Holiday_name
0  01/01  Thursday           0           1  New Years Day
1  01/02    Friday           0           0            NaN
2  01/03  Saturday           1           0            NaN
3  01/04    Sunday           1           0            NaN
4  01/05    Monday           0           0            NaN

In [6]:
dataset = pd.merge(dataset, weekday_features,
                   on='Date', how='inner')
dataset.count()

Unnamed: 0                                    140112
Cooling:Electricity [kW](Hourly)              140112
Date/Time                                     140112
Electricity:Facility [kW](Hourly)             140112
Fans:Electricity [kW](Hourly)                 140112
Gas:Facility [kW](Hourly)                     140112
Heating:Electricity [kW](Hourly)              140112
Heating:Gas [kW](Hourly)                      140112
InteriorEquipment:Electricity [kW](Hourly)    140112
InteriorEquipment:Gas [kW](Hourly)            140112
InteriorLights:Electricity [kW](Hourly)       140112
Water Heater:WaterSystems:Gas [kW](Hourly)    140112
building_type                                 140112
location                                      140112
location_id                                   140112
building_id                                   140112
Date                                          140112
time                                          140112
sunriseTime                                   140112
sunsetTime                                    140112
temperatureHigh                               140112
dewPoint                                      140112
humidity                                      140112
windSpeed                                     140112
cloudCover                                    140112
Electricity:Facility [kW](Hourly)_lag         140112
Electricity:Facility [kW](Hourly)_future      140112
Electricity:Facility_delta_current_lag        140112
Christmas Day                                 140112
Columbus Day                                  140112
Independence Day                              140112
Labor Day                                     140112
Martin Luther King Day                        140112
Memorial Day                                  140112
New Years Day                                 140112
Presidents Day                                140112
Thanksgiving                                  140112
Veterans Day                                  140112
Day                                           140112
is_weekend                                    140112
is_holiday                                    140112
Holiday_name                                    4176
dtype: int64

### One Hot Encoding

In [7]:
dataset['day_of_week'] = dataset['Day']
dataset_expand_days = pd.get_dummies(dataset['Day'])
dataset = pd.concat([dataset, dataset_expand_days], axis=1)
dataset.head(5)

,Unnamed: 0,Cooling:Electricity [kW](Hourly),Date/Time,Electricity:Facility [kW](Hourly),Fans:Electricity [kW](Hourly),Gas:Facility [kW](Hourly),Heating:Electricity [kW](Hourly),Heating:Gas [kW](Hourly),InteriorEquipment:Electricity [kW](Hourly),InteriorEquipment:Gas [kW](Hourly),...,is_holiday,Holiday_name,day_of_week,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,4248,0.0,01/01 01:00:00,92.895587,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,1,New Years Day,Thursday,0,0,0,0,1,0,0
1,4249,0.0,01/01 02:00:00,93.813660,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,1,New Years Day,Thursday,0,0,0,0,1,0,0
2,4250,0.0,01/01 03:00:00,94.444221,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,1,New Years Day,Thursday,0,0,0,0,1,0,0
3,4251,0.0,01/01 04:00:00,96.481468,0.0,2.915538,0.0,0.0,6.812987,1.75125,...,1,New Years Day,Thursday,0,0,0,0,1,0,0
4,4252,0.0,01/01 05:00:00,102.114437,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,1,New Years Day,Thursday,0,0,0,0,1,0,0

In [8]:
dataset.columns

Index(['Unnamed: 0', 'Cooling:Electricity [kW](Hourly)', 'Date/Time',
       'Electricity:Facility [kW](Hourly)', 'Fans:Electricity [kW](Hourly)',
       'Gas:Facility [kW](Hourly)', 'Heating:Electricity [kW](Hourly)',
       'Heating:Gas [kW](Hourly)',
       'InteriorEquipment:Electricity [kW](Hourly)',
       'InteriorEquipment:Gas [kW](Hourly)',
       'InteriorLights:Electricity [kW](Hourly)',
       'Water Heater:WaterSystems:Gas [kW](Hourly)', 'building_type',
       'location', 'location_id', 'building_id', 'Date', 'time', 'sunriseTime',
       'sunsetTime', 'temperatureHigh', 'dewPoint', 'humidity', 'windSpeed',
       'cloudCover', 'Electricity:Facility [kW](Hourly)_lag',
       'Electricity:Facility [kW](Hourly)_future',
       'Electricity:Facility_delta_current_lag', 'Christmas Day',
       'Columbus Day', 'Independence Day', 'Labor Day',
       'Martin Luther King Day', 'Memorial Day', 'New Years Day',
       'Presidents Day', 'Thanksgiving', 'Veterans Day', 'Day', 'is_weekend',
       'is_holiday', 'Holiday_name', 'day_of_week', 'Friday', 'Monday',
       'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday'],
      dtype='object')

In [9]:
dataset_expand_building_type = pd.get_dummies(dataset['building_type'])
dataset = pd.concat([dataset, dataset_expand_building_type], axis=1)
dataset_expand_location = pd.get_dummies(dataset['location'])
dataset = pd.concat([dataset, dataset_expand_location], axis=1)
dataset.head(5)

,Unnamed: 0,Cooling:Electricity [kW](Hourly),Date/Time,Electricity:Facility [kW](Hourly),Fans:Electricity [kW](Hourly),Gas:Facility [kW](Hourly),Heating:Electricity [kW](Hourly),Heating:Gas [kW](Hourly),InteriorEquipment:Electricity [kW](Hourly),InteriorEquipment:Gas [kW](Hourly),...,RefBldgPrimarySchoolNew,RefBldgQuickServiceRestaurantNew,RefBldgSecondarySchoolNew,RefBldgSmallHotelNew,RefBldgSmallOfficeNew,RefBldgStand-aloneRetailNew,RefBldgStripMallNew,RefBldgSuperMarketNew,RefBldgWarehouseNew,USA_CA_LOS_ANGELES
0,4248,0.0,01/01 01:00:00,92.895587,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,0,1,0,1
1,4249,0.0,01/01 02:00:00,93.813660,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,0,1,0,1
2,4250,0.0,01/01 03:00:00,94.444221,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,0,1,0,1
3,4251,0.0,01/01 04:00:00,96.481468,0.0,2.915538,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,0,1,0,1
4,4252,0.0,01/01 05:00:00,102.114437,0.0,1.771250,0.0,0.0,6.812987,1.75125,...,0,0,0,0,0,0,0,1,0,1

In [10]:
dataset['month'] = dataset['Date'].apply(get_month)

In [11]:
dataset.to_csv('../data1/dataset_los_angeles.csv')

In [12]:
dataset[['Electricity:Facility [kW](Hourly)', 'Electricity:Facility [kW](Hourly)_lag',
       'Electricity:Facility [kW](Hourly)_future',
       'Electricity:Facility_delta_current_lag','Date/Time']].head(50)

,Electricity:Facility [kW](Hourly),Electricity:Facility [kW](Hourly)_lag,Electricity:Facility [kW](Hourly)_future,Electricity:Facility_delta_current_lag,Date/Time
0,92.895587,16.375774,14.657581,76.519812,01/01 01:00:00
1,93.813660,16.232981,14.657581,77.580679,01/01 02:00:00
2,94.444221,16.549344,14.657581,77.894877,01/01 03:00:00
3,96.481468,16.248775,14.657581,80.232694,01/01 04:00:00
4,102.114437,16.462351,14.657581,85.652086,01/01 05:00:00
5,98.607770,16.215411,14.657581,82.392359,01/01 06:00:00
6,126.060427,14.896752,12.743414,111.163675,01/01 07:00:00
7,122.862055,7.077384,3.172581,115.784671,01/01 08:00:00
8,164.819273,7.069866,14.006979,157.749407,01/01 09:00:00
9,143.508637,6.617983,14.006979,136.890653,01/01 10:00:00
10,178.744659,6.492824,27.649442,172.251835,01/01 11:00:00
11,206.581840,6.492824,27.649442,200.089016,01/01 12:00:00
12,216.622239,6.492824,36.744417,210.129414,01/01 13:00:00
13,214.638650,6.492824,37.116380,208.145826,01/01 14:00:00
14,209.160486,6.492824,37.586291,202.667662,01/01 15:00:00
15,205.832291,6.492824,37.013192,199.339467,01/01 16:00:00
16,210.689230,9.467158,40.572751,201.222073,01/01 17:00:00
17,192.951663,15.415824,39.134442,177.535838,01/01 18:00:00
18,198.223194,15.415824,30.039467,182.807370,01/01 19:00:00
19,180.661209,15.688692,14.657581,164.972517,01/01 20:00:00
20,167.913382,15.786771,14.657581,152.126611,01/01 21:00:00
21,150.348550,16.108362,14.657581,134.240188,01/01 22:00:00
22,97.505935,16.042497,14.657581,81.463438,01/01 23:00:00
23,129.114563,16.436014,14.657581,112.678549,01/01 24:00:00
24,14.657581,92.895587,11.971293,-78.238006,01/01 01:00:00
25,14.657581,93.813660,11.971293,-79.156079,01/01 02:00:00
26,14.657581,94.444221,11.971293,-79.786640,01/01 03:00:00
27,14.657581,96.481468,11.971293,-81.823888,01/01 04:00:00
28,14.657581,102.114437,11.971293,-87.456856,01/01 05:00:00
29,14.657581,98.607770,11.971293,-83.950189,01/01 06:00:00
30,12.743414,126.060427,10.593626,-113.317013,01/01 07:00:00
31,3.172581,122.862055,3.705293,-119.689474,01/01 08:00:00
32,14.006979,164.819273,18.419764,-150.812294,01/01 09:00:00
33,14.006979,143.508637,18.371483,-129.501658,01/01 10:00:00
34,27.649442,178.744659,33.490019,-151.095217,01/01 11:00:00
35,27.649442,206.581840,33.835329,-178.932398,01/01 12:00:00
36,36.744417,216.622239,44.294329,-179.877821,01/01 13:00:00
37,37.116380,214.638650,44.710157,-177.522270,01/01 14:00:00
38,37.586291,209.160486,44.705103,-171.574195,01/01 15:00:00
39,37.013192,205.832291,44.334317,-168.819099,01/01 16:00:00
40,40.572751,210.689230,46.603340,-170.116480,01/01 17:00:00
41,39.134442,192.951663,41.690161,-153.817221,01/01 18:00:00
42,30.039467,198.223194,31.654504,-168.183727,01/01 19:00:00
43,14.657581,180.661209,11.971293,-166.003628,01/01 20:00:00
44,14.657581,167.913382,11.971293,-153.255801,01/01 21:00:00
45,14.657581,150.348550,11.971293,-135.690969,01/01 22:00:00
46,14.657581,97.505935,11.971293,-82.848354,01/01 23:00:00
47,14.657581,129.114563,11.971293,-114.456982,01/01 24:00:00
48,11.971293,14.657581,4.228019,-2.686288,01/01 01:00:00
49,11.971293,14.657581,4.228019,-2.686288,01/01 02:00:00

In [13]:
"""
data_store = DataStore('35.227.50.121')
data_store.connect_to_database()
data_store.store_data(energystats)
"""

"\ndata_store = DataStore('35.227.50.121')\ndata_store.connect_to_database()\ndata_store.store_data(energystats)\n"